common_metrics = {
    'connections_available': ['connections', 'available'],
    'connections_current': ['connections', 'current'],
    'connections_total_created': ['connections', 'totalCreated'],
    'extra_info_heap_usage_bytes': ['extra_info', 'heap_usage_bytes'],
    'extra_info_page_faults': ['extra_info', 'page_faults'],
    'global_lock_active_clients_readers': ['globalLock', 'activeClients', 'readers'],
    'global_lock_active_clients_total': ['globalLock', 'activeClients', 'total'],
    'global_lock_active_clients_writers': ['globalLock', 'activeClients', 'writers'],
    'global_lock_current_queue_readers': ['globalLock', 'currentQueue', 'readers'],
    'global_lock_current_queue_total': ['globalLock', 'currentQueue', 'total'],
    'global_lock_current_queue_writers': ['globalLock', 'currentQueue', 'writers'],
    'global_lock_total_time': ['globalLock', 'totalTime'],
    # Omitting "Locks"
    'network_bytes_in': ['network', 'bytesIn'],
    'network_bytes_out': ['network', 'bytesOut'],
    'network_num_requests': ['network', 'numRequests'],
    'opcounters_command': ['opcounters', 'command'],
    'opcounters_delete': ['opcounters', 'delete'],
    'opcounters_getmore': ['opcounters', 'getmore'],
    'opcounters_insert': ['opcounters', 'insert'],
    'opcounters_query': ['opcounters', 'query'],
    'opcounters_update': ['opcounters', 'update'],
    'opcounters_replication_command': ['opcountersRepl', 'command'],
    'opcounters_replication_delete': ['opcountersRepl', 'delete'],
    'opcounters_replication_getmore': ['opcountersRepl', 'getmore'],
    'opcounters_replication_insert': ['opcountersRepl', 'insert'],
    'opcounters_replication_query': ['opcountersRepl', 'query'],
    'opcounters_replication_update': ['opcountersRepl', 'update'],
    'tcmalloc_generic_current_allocated_bytes': ['tcmalloc', 'generic', 'current_allocated_bytes'],
    'tcmalloc_generic_heap_size': ['tcmalloc', 'generic', 'heap_size'],
    'tcmalloc_tcmalloc_aggressive_memory_decommit': ['tcmalloc', 'tcmalloc', 'aggressive_memory_decommit'],
    'tcmalloc_tcmalloc_central_cache_free_bytes': ['tcmalloc', 'tcmalloc', 'central_cache_free_bytes'],
    'tcmalloc_tcmalloc_current_total_thread_cache_bytes': ['tcmalloc', 'tcmalloc', 'current_total_thread_cache_bytes'],
    'tcmalloc_tcmalloc_max_total_thread_cache_bytes': ['tcmalloc', 'tcmalloc', 'max_total_thread_cache_bytes'],
    'tcmalloc_tcmalloc_pageheap_free_bytes': ['tcmalloc', 'tcmalloc', 'pageheap_free_bytes'],
    'tcmalloc_tcmalloc_pageheap_unmapped_bytes': ['tcmalloc', 'tcmalloc', 'pageheap_unmapped_bytes'],
    'tcmalloc_tcmalloc_thread_cache_free_bytes': ['tcmalloc', 'tcmalloc', 'thread_cache_free_bytes'],
    'tcmalloc_tcmalloc_transfer_cache_free_bytes': ['tcmalloc', 'tcmalloc', 'transfer_cache_free_bytes'],
    'mem_resident': ['mem', 'resident'],
    'mem_virtual': ['mem', 'virtual'],
    'mem_mapped': ['mem', 'mapped'],
    'mem_mapped_with_journal': ['mem', 'mappedWithJournal'],
    # TODO - Add in the rest of the metrics.commands output
    'metrics_commands_aggregate_failed': ['metrics', 'commands', 'aggregate', 'failed'],
    'metrics_commands_aggregate_total': ['metrics', 'commands', 'aggregate', 'total'],
    'metrics_commands_findAndModify_failed': ['metrics', 'commands', 'findAndModify', 'failed'],
    'metrics_commands_findAndModify_total': ['metrics', 'commands', 'findAndModify', 'total'],
    'metrics_cursor_timed_out': ['metrics', 'cursor', 'timedOut'],
    'metrics_cursor_open_notimeout': ['metrics', 'cursor', 'open', 'noTimeout'],
    'metrics_cursor_open_pinned': ['metrics', 'cursor', 'open', 'pinned'],
    'metrics_cursor_open_total': ['metrics', 'cursor', 'open', 'total'],
    'metrics_document_deleted': ['metrics', 'document', 'deleted'],
    'metrics_document_inserted': ['metrics', 'document', 'inserted'],
    'metrics_document_returned': ['metrics', 'document', 'returned'],
    'metrics_document_updated': ['metrics', 'document', 'updated'],
    'metrics_operation_fastmod': ['metrics', 'operation', 'fastmod'],
    'metrics_operation_idhack': ['metrics', 'operation', 'idhack'],
    'metrics_operation_scanAndOrder': ['metrics', 'operation', 'scanAndOrder'],
    'metrics_operation_writeConflicts': ['metrics', 'operation', 'writeConflicts'],
    'metrics_storage_freelist_search_bucketExhausted': ['metrics', 'storage', 'freelist', 'search', 'bucketExhausted'],
    'metrics_storage_freelist_search_requests': ['metrics', 'storage', 'freelist', 'search', 'requests'],
    'metrics_storage_freelist_search_scanned': ['metrics', 'storage', 'freelist', 'search', 'scanned'],
}

mmapv1_metrics = {
    'background_flushing_flushes': ['backgroundFlushing', 'flushes'],
    'background_flushing_total_ms': ['backgroundFlushing', 'total_ms'],
    'background_flushing_average_ms': ['backgroundFlushing', 'average_ms'],
    'background_flushing_last_ms': ['backgroundFlushing', 'last_ms'],
    'journal_commits': ['dur', 'commits'],
    'journal_MB_written_to_journal': ['dur', 'journaledMB'],
    'journal_MB_written_to_datafiles': ['dur', 'writeToDataFilesMB'],
    'journal_compression': ['dur', 'compression'],
    'journal_commits_during_write_lock': ['dur', 'commitsInWriteLock'],
    'journal_earlycommits': ['dur', 'earlyCommits']
    # TODO: Add in the journalling timeMS (dur.timeMS) metrics
}

# Created using:
# for section in ss['wiredTiger'].keys():
#     if isinstance(ss['wiredTiger'][section], dict):
#         for fieldname in ss['wiredTiger'][section].keys():
#             print("'wt_{}_{}': ['wiredTiger', '{}', '{}'],".format(section, fieldname.replace(' ', '_'), section, fieldname))
wiredtiger_metrics = {
    # Omitting the LSM and async sections
    'block-manager_bytes_read': ['wiredTiger', 'block-manager', 'bytes read'],
    'block-manager_blocks_written': ['wiredTiger', 'block-manager', 'blocks written'],
    'block-manager_blocks_pre-loaded': ['wiredTiger', 'block-manager', 'blocks pre-loaded'],
    'block-manager_bytes_written': ['wiredTiger', 'block-manager', 'bytes written'],
    'block-manager_mapped_bytes_read': ['wiredTiger', 'block-manager', 'mapped bytes read'],
    'block-manager_blocks_read': ['wiredTiger', 'block-manager', 'blocks read'],
    'block-manager_mapped_blocks_read': ['wiredTiger', 'block-manager', 'mapped blocks read'],
    'log_total_log_buffer_size': ['wiredTiger', 'log', 'total log buffer size'],
    'log_log_read_operations': ['wiredTiger', 'log', 'log read operations'],
    'log_slots_selected_for_switching_that_were_unavailable': ['wiredTiger', 'log', 'slots selected for switching that were unavailable'],
    'log_consolidated_slot_closures': ['wiredTiger', 'log', 'consolidated slot closures'],
    'log_consolidated_slot_joins': ['wiredTiger', 'log', 'consolidated slot joins'],
    'log_log_records_too_small_to_compress': ['wiredTiger', 'log', 'log records too small to compress'],
    'log_log_sync_dir_operations': ['wiredTiger', 'log', 'log sync_dir operations'],
    'log_log_scan_records_requiring_two_reads': ['wiredTiger', 'log', 'log scan records requiring two reads'],
    'log_log_buffer_size_increases': ['wiredTiger', 'log', 'log buffer size increases'],
    'log_log_write_operations': ['wiredTiger', 'log', 'log write operations'],
    'log_maximum_log_file_size': ['wiredTiger', 'log', 'maximum log file size'],
    'log_yields_waiting_for_previous_log_file_close': ['wiredTiger', 'log', 'yields waiting for previous log file close'],
    'log_record_size_exceeded_maximum': ['wiredTiger', 'log', 'record size exceeded maximum'],
    'log_log_records_compressed': ['wiredTiger', 'log', 'log records compressed'],
    'log_total_size_of_compressed_records': ['wiredTiger', 'log', 'total size of compressed records'],
    'log_log_records_not_compressed': ['wiredTiger', 'log', 'log records not compressed'],
    'log_total_in-memory_size_of_compressed_records': ['wiredTiger', 'log', 'total in-memory size of compressed records'],
    'log_log_bytes_written': ['wiredTiger', 'log', 'log bytes written'],
    'log_log_bytes_of_payload_data': ['wiredTiger', 'log', 'log bytes of payload data'],
    'log_log_scan_operations': ['wiredTiger', 'log', 'log scan operations'],
    'log_log_server_thread_advances_write_LSN': ['wiredTiger', 'log', 'log server thread advances write LSN'],
    'log_log_sync_operations': ['wiredTiger', 'log', 'log sync operations'],
    'log_consolidated_slot_join_races': ['wiredTiger', 'log', 'consolidated slot join races'],
    'log_logging_bytes_consolidated': ['wiredTiger', 'log', 'logging bytes consolidated'],
    'log_failed_to_find_a_slot_large_enough_for_record': ['wiredTiger', 'log', 'failed to find a slot large enough for record'],
    'log_log_release_advances_write_LSN': ['wiredTiger', 'log', 'log release advances write LSN'],
    'log_pre-allocated_log_files_used': ['wiredTiger', 'log', 'pre-allocated log files used'],
    'log_consolidated_slot_join_transitions': ['wiredTiger', 'log', 'consolidated slot join transitions'],
    'log_number_of_pre-allocated_log_files_to_create': ['wiredTiger', 'log', 'number of pre-allocated log files to create'],
    'log_records_processed_by_log_scan': ['wiredTiger', 'log', 'records processed by log scan'],
    'log_pre-allocated_log_files_prepared': ['wiredTiger', 'log', 'pre-allocated log files prepared'],
    'cache_eviction_server_candidate_queue_empty_when_topping_up': ['wiredTiger', 'cache', 'eviction server candidate queue empty when topping up'],
    'cache_pages_evicted_because_they_exceeded_the_in-memory_maximum': ['wiredTiger', 'cache', 'pages evicted because they exceeded the in-memory maximum'],
    'cache_page_split_during_eviction_deepened_the_tree': ['wiredTiger', 'cache', 'page split during eviction deepened the tree'],
    'cache_maximum_page_size_at_eviction': ['wiredTiger', 'cache', 'maximum page size at eviction'],
    'cache_pages_walked_for_eviction': ['wiredTiger', 'cache', 'pages walked for eviction'],
    'cache_tracked_bytes_belonging_to_leaf_pages_in_the_cache': ['wiredTiger', 'cache', 'tracked bytes belonging to leaf pages in the cache'],
    'cache_pages_written_from_cache': ['wiredTiger', 'cache', 'pages written from cache'],
    'cache_failed_eviction_of_pages_that_exceeded_the_in-memory_maximum': ['wiredTiger', 'cache', 'failed eviction of pages that exceeded the in-memory maximum'],
    'cache_pages_evicted_because_they_had_chains_of_deleted_items': ['wiredTiger', 'cache', 'pages evicted because they had chains of deleted items'],
    'cache_pages_split_during_eviction': ['wiredTiger', 'cache', 'pages split during eviction'],
    'cache_bytes_read_into_cache': ['wiredTiger', 'cache', 'bytes read into cache'],
    'cache_tracked_dirty_bytes_in_the_cache': ['wiredTiger', 'cache', 'tracked dirty bytes in the cache'],
    'cache_pages_currently_held_in_the_cache': ['wiredTiger', 'cache', 'pages currently held in the cache'],
    'cache_tracked_dirty_pages_in_the_cache': ['wiredTiger', 'cache', 'tracked dirty pages in the cache'],
    'cache_bytes_currently_in_the_cache': ['wiredTiger', 'cache', 'bytes currently in the cache'],
    'cache_tracked_bytes_belonging_to_overflow_pages_in_the_cache': ['wiredTiger', 'cache', 'tracked bytes belonging to overflow pages in the cache'],
    'cache_modified_pages_evicted': ['wiredTiger', 'cache', 'modified pages evicted'],
    'cache_pages_read_into_cache': ['wiredTiger', 'cache', 'pages read into cache'],
    'cache_eviction_server_unable_to_reach_eviction_goal': ['wiredTiger', 'cache', 'eviction server unable to reach eviction goal'],
    'cache_internal_pages_evicted': ['wiredTiger', 'cache', 'internal pages evicted'],
    'cache_checkpoint_blocked_page_eviction': ['wiredTiger', 'cache', 'checkpoint blocked page eviction'],
    'cache_pages_evicted_by_application_threads': ['wiredTiger', 'cache', 'pages evicted by application threads'],
    'cache_in-memory_page_splits': ['wiredTiger', 'cache', 'in-memory page splits'],
    'cache_percentage_overhead': ['wiredTiger', 'cache', 'percentage overhead'],
    'cache_bytes_written_from_cache': ['wiredTiger', 'cache', 'bytes written from cache'],
    'cache_maximum_bytes_configured': ['wiredTiger', 'cache', 'maximum bytes configured'],
    'cache_hazard_pointer_blocked_page_eviction': ['wiredTiger', 'cache', 'hazard pointer blocked page eviction'],
    'cache_pages_selected_for_eviction_unable_to_be_evicted': ['wiredTiger', 'cache', 'pages selected for eviction unable to be evicted'],
    'cache_eviction_server_evicting_pages': ['wiredTiger', 'cache', 'eviction server evicting pages'],
    'cache_eviction_worker_thread_evicting_pages': ['wiredTiger', 'cache', 'eviction worker thread evicting pages'],
    'cache_eviction_server_candidate_queue_not_empty_when_topping_up': ['wiredTiger', 'cache', 'eviction server candidate queue not empty when topping up'],
    'cache_unmodified_pages_evicted': ['wiredTiger', 'cache', 'unmodified pages evicted'],
    'cache_eviction_server_populating_queue,_but_not_evicting_pages': ['wiredTiger', 'cache', 'eviction server populating queue, but not evicting pages'],
    'cache_tracked_bytes_belonging_to_internal_pages_in_the_cache': ['wiredTiger', 'cache', 'tracked bytes belonging to internal pages in the cache'],
    'transaction_transaction_checkpoint_generation': ['wiredTiger', 'transaction', 'transaction checkpoint generation'],
    'transaction_transaction_checkpoints': ['wiredTiger', 'transaction', 'transaction checkpoints'],
    'transaction_transaction_checkpoint_min_time_(msecs)': ['wiredTiger', 'transaction', 'transaction checkpoint min time (msecs)'],
    'transaction_transaction_begins': ['wiredTiger', 'transaction', 'transaction begins'],
    'transaction_transaction_checkpoint_currently_running': ['wiredTiger', 'transaction', 'transaction checkpoint currently running'],
    'transaction_transaction_range_of_IDs_currently_pinned': ['wiredTiger', 'transaction', 'transaction range of IDs currently pinned'],
    'transaction_transaction_checkpoint_max_time_(msecs)': ['wiredTiger', 'transaction', 'transaction checkpoint max time (msecs)'],
    'transaction_transaction_checkpoint_total_time_(msecs)': ['wiredTiger', 'transaction', 'transaction checkpoint total time (msecs)'],
    'transaction_transaction_failures_due_to_cache_overflow': ['wiredTiger', 'transaction', 'transaction failures due to cache overflow'],
    'transaction_transaction_checkpoint_most_recent_time_(msecs)': ['wiredTiger', 'transaction', 'transaction checkpoint most recent time (msecs)'],
    'transaction_transactions_rolled_back': ['wiredTiger', 'transaction', 'transactions rolled back'],
    'transaction_transaction_range_of_IDs_currently_pinned_by_a_checkpoint': ['wiredTiger', 'transaction', 'transaction range of IDs currently pinned by a checkpoint'],
    'transaction_transactions_committed': ['wiredTiger', 'transaction', 'transactions committed'],
    'connection_total_write_I/Os': ['wiredTiger', 'connection', 'total write I/Os'],
    'connection_pthread_mutex_condition_wait_calls': ['wiredTiger', 'connection', 'pthread mutex condition wait calls'],
    'connection_pthread_mutex_shared_lock_write-lock_calls': ['wiredTiger', 'connection', 'pthread mutex shared lock write-lock calls'],
    'connection_total_read_I/Os': ['wiredTiger', 'connection', 'total read I/Os'],
    'connection_memory_frees': ['wiredTiger', 'connection', 'memory frees'],
    'connection_memory_allocations': ['wiredTiger', 'connection', 'memory allocations'],
    'connection_files_currently_open': ['wiredTiger', 'connection', 'files currently open'],
    'connection_pthread_mutex_shared_lock_read-lock_calls': ['wiredTiger', 'connection', 'pthread mutex shared lock read-lock calls'],
    'connection_memory_re-allocations': ['wiredTiger', 'connection', 'memory re-allocations'],
    'session_open_session_count': ['wiredTiger', 'session', 'open session count'],
    'session_open_cursor_count': ['wiredTiger', 'session', 'open cursor count'],
    'data-handle_session_sweep_attempts': ['wiredTiger', 'data-handle', 'session sweep attempts'],
    'data-handle_session_dhandles_swept': ['wiredTiger', 'data-handle', 'session dhandles swept'],
    'data-handle_connection_time-of-death_sets': ['wiredTiger', 'data-handle', 'connection time-of-death sets'],
    'data-handle_connection_dhandles_swept': ['wiredTiger', 'data-handle', 'connection dhandles swept'],
    'data-handle_connection_candidate_referenced': ['wiredTiger', 'data-handle', 'connection candidate referenced'],
    'data-handle_connection_sweeps': ['wiredTiger', 'data-handle', 'connection sweeps'],
    'cursor_cursor_update_calls': ['wiredTiger', 'cursor', 'cursor update calls'],
    'cursor_cursor_create_calls': ['wiredTiger', 'cursor', 'cursor create calls'],
    'cursor_cursor_remove_calls': ['wiredTiger', 'cursor', 'cursor remove calls'],
    'cursor_cursor_reset_calls': ['wiredTiger', 'cursor', 'cursor reset calls'],
    'cursor_cursor_next_calls': ['wiredTiger', 'cursor', 'cursor next calls'],
    'cursor_cursor_search_near_calls': ['wiredTiger', 'cursor', 'cursor search near calls'],
    'cursor_cursor_search_calls': ['wiredTiger', 'cursor', 'cursor search calls'],
    'cursor_cursor_insert_calls': ['wiredTiger', 'cursor', 'cursor insert calls'],
    'cursor_cursor_prev_calls': ['wiredTiger', 'cursor', 'cursor prev calls'],
    'thread-yield_page_acquire_eviction_blocked': ['wiredTiger', 'thread-yield', 'page acquire eviction blocked'],
    'thread-yield_page_acquire_busy_blocked': ['wiredTiger', 'thread-yield', 'page acquire busy blocked'],
    'thread-yield_page_acquire_locked_blocked': ['wiredTiger', 'thread-yield', 'page acquire locked blocked'],
    'thread-yield_page_acquire_time_sleeping_(usecs)': ['wiredTiger', 'thread-yield', 'page acquire time sleeping (usecs)'],
    'thread-yield_page_acquire_read_blocked': ['wiredTiger', 'thread-yield', 'page acquire read blocked'],
    'concurrentTransactions_read_out': ['wiredTiger', 'concurrentTransactions', 'read', 'out'],
    'concurrentTransactions_read_available': ['wiredTiger', 'concurrentTransactions', 'read', 'available'],
    'concurrentTransactions_read_totalTickets': ['wiredTiger', 'concurrentTransactions', 'read', 'totalTickets'],
    'concurrentTransactions_write_out': ['wiredTiger', 'concurrentTransactions', 'write', 'out'],
    'concurrentTransactions_write_available': ['wiredTiger', 'concurrentTransactions', 'write', 'available'],
    'concurrentTransactions_write_totalTickets': ['wiredTiger', 'concurrentTransactions', 'write', 'totalTickets'],
    'reconciliation_page_reconciliation_calls': ['wiredTiger', 'reconciliation', 'page reconciliation calls'],
    'reconciliation_page_reconciliation_calls_for_eviction': ['wiredTiger', 'reconciliation', 'page reconciliation calls for eviction'],
    'reconciliation_split_objects_currently_awaiting_free': ['wiredTiger', 'reconciliation', 'split objects currently awaiting free'],
    'reconciliation_split_bytes_currently_awaiting_free': ['wiredTiger', 'reconciliation', 'split bytes currently awaiting free'],
}